### ISSUE TITLE
[Feature Request] Show more details in logError

### ISSUE THREAD

**Issue by SvenJuergens** [Mister-Hope/gulp-sass#488]
when I get an error in my SCSS file, I get an error message with little information.
In my opinion, this was more detailed in the past as well.
Maybe it is possible to add a more advanced option for the logError function.

This is my standard output:
![original-w](https://user-images.githubusercontent.com/20923295/181575338-a763fe0d-1c6c-476b-9b0f-c0ca0bb043bb.png)

I find this output more helpful:
![with-messageOriginal-w](https://user-images.githubusercontent.com/20923295/181575363-58166eb9-632e-4fcc-8af5-dc851e474c82.png)

this is my default gulpfile
```
const { sass } = require("@mr-hope/gulp-sass");
....

function css() {
  return src(paths.scss)
    .pipe(sass({style: 'compressed'}).on("error", sass.logError))
    .pipe(autoprefixer({
      cascade: false
    }))
    .pipe(dest(paths.destinationCss));
}
....

```

package.json:
```
...
    "@mr-hope/gulp-sass": "^3.0.2",
    "gulp": "^4.0.2",
...
```
Node 16 on Linux Mint 20.03

**Comment by Mister-Hope** [comment]
Sorry I totally fogot this, I will check this now

**Comment by Mister-Hope** [comment]
https://github.com/Mister-Hope/gulp-sass/commit/efa27908694df0f416845d4ab342a91a2417f33b
