### ISSUE TITLE
[Feature Request] Add the ability to use grass instead of dart-sass

### ISSUE THREAD

**Issue by Atulin** [Mister-Hope/gulp-sass#652]
**Describe the feature and why you wanted**
[Grass](https://github.com/connorskees/grass) promises 2x performance gains over dart-sass. It would be nice to be able to use it with gulp-sass, perhaps by setting some parameter in the options, or even being able to provide your own SASS implementation. For example

```js
.pipe(sass({ compiler: 'grass' /* default being 'dart-sass' */ }))
```

or

```js
import * as grass from 'grass';
import * as sass from 'sass';

const useGrass = true;

.pipe(sass({ compiler: useGrass ? grass : sass }))
```

**Comment by Mister-Hope** [comment]
Where is your grass pkg?

**Comment by Atulin** [comment]
Uh, it would be installed [via NPM](https://www.npmjs.com/package/@connorskees/grass), presumably?

**Comment by Mister-Hope** [comment]
It has nearly no options, so how can I integrate it?

probably this should.be.built.as a new package called gulp-grass or any thing else.

**Comment by Mister-Hope** [comment]
Also one more thing, you mention 2 times faster, not 10x faster like esbuild, so I have little interest because I am not expecting anyone to hit a performance issue when playing tons of sass files with gulp.
